version: '3.3'

services:
  db:
    # container_name: db-wordpress
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: wordpress
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: wordpress
    #   MYSQL_PASSWORD: wordpress
    networks:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    # environment:
    #   WORDPRESS_DB_HOST: db:3306
    #   WORDPRESS_DB_USER: wordpress
    #   WORDPRESS_DB_PASSWORD: wordpress
    #   WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress

volumes:
  db_data: {}
networks:
  wordpress:
    driver: bridge